### ISSUE TITLE
Docker ejercicio 3

### ISSUE THREAD

**Issue by Emili0Taib0** [ThePableras/Docker_grupo#2]
Tengo una duda sobre si este comando esta bien:
- Crea un contenedor con una imagen de mariaDB que estará en la red redbd . Este
contenedor se ejecutará en segundo plano, y será accesible a través del puerto 3306. (Es
necesario definir la contraseña del usuario root y un volumen de datos persistente):
docker run -d --name mariadb --network redbd -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 mariadb
Y tambien en como crear un contenedor que se pueda conectar al contenedor de la Base de Datos

**Comment by ThePableras** [comment]
Está correcto con la salvedad de que falta definir en el comando el almancenamiento persistente.

Por ejemplo;
`adduser mariadb`
`docker run -d --name mariadb --network redbd -v mariadb:/home/mariadb -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 mariadb`
