### ISSUE TITLE
Duda con un comando

### ISSUE THREAD

**Issue by Emili0Taib0** [ThePableras/Docker_grupo#4]
Me pide crear un contenedor con Adminer que se pueda conectar al contenedor de la BD
Tengo duda si este comando sirve pero con el link bien (no se cual es el link).
`docker run --link -p 8080:8080 adminer`

**Comment by ThePableras** [comment]
El comando a utilizar es
`docker run --link mariadb: -e POSTGRES_USER=root -e POSTGRES_PASSWORD=root -e POSTGRES_DB=adminer -p 8080:8080 adminer`
